% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Analysis of the heart weights of cats},
  pdfauthor={Student Number: 2516212c},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Analysis of the heart weights of cats}
\author{Student Number: 2516212c}
\date{}

\begin{document}
\maketitle

\hypertarget{sec:intro}{%
\section{Introduction}\label{sec:intro}}

Experiments were conducted as part of research into ``Digitails'', a
heart medicine similar to toxins found in plants commonly known as
foxglove. 144 domestic male and female adult cats were used in the
experiments and they each had their heart weight in grams(Hwt) measured.
This data, including the sex(Sex) of each cat, is analysed in this
report.

\hypertarget{sec:EDA}{%
\section{Exploratory Data Analysis}\label{sec:EDA}}

Summary statistics of the heart weights of the cats are presented in the
following table for each sex separately.

\begin{table}[!h]

\caption{\label{tab:summaries}\label{tab:summarises} Summary statistics on heart weight by sex of 144 adult cats}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r|r|r}
\hline
Sex & n & Mean & St.Dev & Min & Q1 & Median & Q3 & Max\\
\hline
F & 47 & 9.2 & 1.4 & 6.3 & 8.35 & 9.1 & 10.1 & 13.0\\
\hline
M & 97 & 11.3 & 2.5 & 6.5 & 9.40 & 11.4 & 12.8 & 20.5\\
\hline
\end{tabular}
\end{table}

This table shows that there were approximately twice as many cats in the
sample(97 compared to 47) and that the summarises of the heart weights
of the male cats were consistently greater than the corresponding
summarises of the heart weights of female cats. For example the mean
heart weight of the male cats was 11.3 grams compared to 9.2 grams for
the mean heart weight of cats. We also note that the variability in the
male hearts' weights, as measured by the standard deviation of 2.5
grams, was nearly twice as much as the standard deviation of 1.4 grams
for the female hearts' weights. These differences can be easily seen in
the follwing boxplots which summarise the distribution of the heart
weights of male and female cats.

\begin{figure}[H]

{\centering \includegraphics[width=0.68\linewidth]{BasicTemplate_files/figure-latex/boxplot1-1} 

}

\caption{\label{fig:box} Heart weight by Sex}\label{fig:boxplot1}
\end{figure}

The boxplot shows that the male cats having heavier hearts, in general,
compared to the female cats' hearts and that the weights of the male
hearts were more widely distributed. There are also potentially two
outliers(one male and one female) which have unusually heavy hearts, as
shown by the two points shown beyond the ``whiskers'' of the boxplots.

\hypertarget{sec:FDA}{%
\section{Formal Data Analysis}\label{sec:FDA}}

To begin to analyse the cat heart weights data formally, we fit the
following linear model to the data.

\[\widehat{\mbox{Hei}} = \widehat{\alpha} + \widehat{\beta}_{\mbox{F}} \cdot \mathbb{I}_{\mbox{F}}(x)\]
Where \(\widehat{\mbox{Hwt}}\) is the expected value of the heart weight
of the \(i\)th cat in the sample; the intercept \(\widehat{\alpha}\) is
the mean heart weight for the baseline category of females;
\(\widehat{\beta}_{Male}\) is the difference in the mean heart weight of
a males relatively to the baseline category females;
\(\mathbb{I}_{Male}(i)\) is an indicator function such that
\[\mathbb{I}_{\mbox{Male}}(i)=\left\{
\begin{array}{ll}
1 ~~~ \mbox{if Sex of} ~ i \mbox{th observation is Male},\\
0 ~~~ \mbox{Otherwise}.\\
\end{array}
\right.\] When this model is fitted to the data, the following estimates
of \(\alpha\)(intercept) and \(\beta_{Male}(SexM)\) are returned:

\begin{table}[!h]

\caption{\label{tab:modeltable}\label{tab:reg} Estimates of the parameters from the fitted linear regression model.}
\centering
\begin{tabular}[t]{l|r}
\hline
term & estimate\\
\hline
intercept & 9.202\\
\hline
SexM & 2.121\\
\hline
\end{tabular}
\end{table}

Hence the model estimates the average heart weight of female cats is
9.202 grams (which agrees with the sample mean reported in Table
\ref{tab:summarises}) and that the male cats' heart weights are, on
average, 2.121 grams heavier than the female cats' heart weights.

Before we can proceed to use the fitted model(for example to perform
statistical inference) we must check the assumptions of the model. These
are best considered in light of the residual plots in Figure 2.

\begin{figure}[H]

{\centering \includegraphics{BasicTemplate_files/figure-latex/doubleplots-1} 

}

\caption{\label{fig:resids} Scatterplots of the residuals by Sex(left) and a histogram of the residuals (right)}\label{fig:doubleplots}
\end{figure}

The scatterplots show an approximately even spread of the residuals
above and below the zero line for each gender, and hence the assumption
that the residuals have mean zero appears valid. The assumption of
constant variance within the two genders is not supported, however, as
the spread of the residuals in the vertical scatter of the male cats is
considerably more than that of females(as was noted above when the
standard deviations were considered). The histogram supports the
assumption of normally distributed errors in the model, which the
exception of a potential outlier.

\[\widehat{\mbox{Height_cm}} = \widehat{\alpha} + \widehat{\beta}_{\mbox{F}} \cdot \mathbb{I}_{\mbox{F}}(x)\]
Where \(\widehat{\mbox{Height_cm}}\) is the expected value of the heart
weight of the \(i\)th cat in the sample; the intercept
\(\widehat{\alpha}\) is the mean heart weight for the baseline category
of females; \(\widehat{\beta}_{F}\) is the difference in the mean heart
weight of a males relatively to the baseline category females;
\(\mathbb{I}_{F}(i)\) is an indicator function such that
\[\mathbb{I}_{\mbox{F}}(i)=\left\{
  \begin{array}{ll}
  1 ~~~ \mbox{if position of} ~ i \mbox{th observation is Forward},\\
  0 ~~~ \mbox{Otherwise}.\\
  \end{array}
  \right.\] When this model is fitted to the data, the following
estimates of \(\alpha\)(intercept) and \(\beta_{Forw}(PosF)\) are
returned:

\hypertarget{sec:Conc}{%
\section{Conclusions}\label{sec:Conc}}

In summary, we have estimated that, on averagem the male cats have
hearts which weigh 2.121 grams more than the female cats' hearts. In
particular, we estimate the average heart weight of female cats is 9.202
grams and the average heart weight of male cats is 11.3 grams.

In addition to the centers of the distributions of male and female cats'
heart weights being different, we have also observed that the spread of
the male heart weights is greater than the spread of the female cats'
heart weights. This may pose a problem if the standard linear model was
used to further analyse this data, and therefore it is recommended that
models which allow for differences in the variances with in different
groups be used.

\hypertarget{task-2.-further-task}{%
\section{Task 2. Further Task}\label{task-2.-further-task}}

Further Task Part a.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Glasgow\_Ed\_SIMD2020 }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"Glasgow\_Edinburgh\_SIMD2020.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

This data is not in tidy format since the measurement of interest is
`rank' of which there are 8 types(i.e.~SMID, Income, Employment, Health,
Education, Access, Crime and Housing) spread over 8 columns. In tidy
format, the `rank' measurements should be in a single column, with a
separate column indicating the type of `rank'.

To convert the data into a tidy format, use

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Glasgow\_Ed\_SIMD2020\_tidy1 }\OtherTok{\textless{}{-}} \FunctionTok{gather}\NormalTok{(}\AttributeTok{data =}\NormalTok{ Glasgow\_Ed\_SIMD2020,}
\AttributeTok{key =}\NormalTok{ Type\_of\_Rank, }\AttributeTok{value =}\NormalTok{ Rank,}
\NormalTok{SIMD\_Rank}\SpecialCharTok{:}\NormalTok{Housing\_Rank)}

\NormalTok{Glasgow\_Ed\_SIMD2020\_tidy1}\SpecialCharTok{$}\NormalTok{Type\_of\_Rank }\OtherTok{\textless{}{-}} 
  \FunctionTok{str\_replace}\NormalTok{(Glasgow\_Ed\_SIMD2020\_tidy1}\SpecialCharTok{$}\NormalTok{Type\_of\_Rank, }\StringTok{"\_Rank"}\NormalTok{, }\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Gla\_Ed\_SIMD2020 }\OtherTok{\textless{}{-}}\NormalTok{ Glasgow\_Ed\_SIMD2020\_tidy1 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(Type\_of\_Rank }\SpecialCharTok{==} \StringTok{"SIMD"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Perc\_Working\_Age =} \DecValTok{100} \SpecialCharTok{*}\NormalTok{ Working\_Age\_population}\SpecialCharTok{/}\NormalTok{Total\_population)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Gla\_Ed\_SIMD2020 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Perc\_Working\_Age,}\AttributeTok{y=}\NormalTok{Rank,}\AttributeTok{group=}\NormalTok{Council\_area,}\AttributeTok{color=}\NormalTok{Council\_area))}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Percentage of population of working age"}\NormalTok{, }\AttributeTok{y =} \StringTok{"SIMD2020 Rank"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning: Removed 3 rows containing missing values (geom_point).
\end{verbatim}

\includegraphics{BasicTemplate_files/figure-latex/unnamed-chunk-5-1.pdf}

\end{document}
